# Generated by Django 2.1.7 on 2019-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudUsdH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EurUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EurUsdH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GbpUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GbpUsdH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoldH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NzdUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NzdUsdH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdCadDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdCadH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdChfDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdChfH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdJpyDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsdJpyH8',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
