# Generated by Django 2.2.1 on 2019-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_greed'),
    ]

    operations = [
        migrations.AddField(
            model_name='greed',
            name='right_bar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
