# Generated by Django 2.2.1 on 2019-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_greed_str_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greed',
            name='str_datetime',
            field=models.TextField(),
        ),
    ]
