# Generated by Django 2.2.1 on 2019-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20190910_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greed',
            name='last_update',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='greed',
            name='str_last_update',
            field=models.TextField(),
        ),
    ]
