# Generated by Django 2.2.1 on 2019-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_auto_20190920_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first',
            old_name='gain',
            new_name='gain_main',
        ),
        migrations.AddField(
            model_name='first',
            name='c',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
