# Generated by Django 2.2.1 on 2019-09-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_auto_20190920_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='gain',
            field=models.FloatField(null=True),
        ),
    ]
