# Generated by Django 2.2.1 on 2019-09-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0021_auto_20190926_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XauUsdDaily',
        ),
    ]
