# Generated by Django 2.2.1 on 2019-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0022_delete_xauusddaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='XauUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
