# Generated by Django 2.2.1 on 2019-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0024_spx500usddaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcoUsdDaily',
            fields=[
                ('t', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
