# Generated by Django 2.2.1 on 2019-08-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_audusdh4_eurusdh4_gbpusdh4_goldh4_nzdusdh4_usdcadh4_usdchfh4_usdjpyh4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.PositiveIntegerField()),
                ('currency', models.TextField()),
                ('history', models.PositiveIntegerField()),
                ('gain', models.FloatField(null=True)),
                ('state', models.TextField(null=True)),
                ('direction', models.TextField(null=True)),
                ('o', models.PositiveIntegerField(null=True)),
                ('c', models.PositiveIntegerField(null=True)),
                ('oanda', models.PositiveIntegerField(null=True)),
            ],
            options={
                'unique_together': {('t', 'currency')},
            },
        ),
    ]
