# Generated by Django 2.2.1 on 2019-09-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20190904_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greed',
            name='right_bar',
        ),
    ]
