# Generated by Django 2.2.1 on 2019-09-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_remove_greed_right_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='greed',
            name='last_update',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='greed',
            name='str_last_update',
            field=models.TextField(null=True),
        ),
    ]
