# Generated by Django 2.2.1 on 2019-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20190910_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.PositiveIntegerField()),
                ('currency', models.TextField()),
                ('history', models.PositiveIntegerField()),
                ('gain', models.FloatField()),
                ('state', models.TextField(null=True)),
                ('direction', models.TextField()),
                ('c', models.PositiveIntegerField()),
                ('oanda', models.PositiveIntegerField(null=True)),
                ('str_datetime', models.TextField()),
            ],
            options={
                'unique_together': {('t', 'currency')},
            },
        ),
    ]
