# Generated by Django 2.2.1 on 2019-09-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_remove_third_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudUsdH4',
        ),
        migrations.DeleteModel(
            name='AudUsdH8',
        ),
        migrations.DeleteModel(
            name='EurUsdH4',
        ),
        migrations.DeleteModel(
            name='EurUsdH8',
        ),
        migrations.DeleteModel(
            name='GbpUsdH4',
        ),
        migrations.DeleteModel(
            name='GbpUsdH8',
        ),
        migrations.DeleteModel(
            name='GoldH4',
        ),
        migrations.DeleteModel(
            name='GoldH8',
        ),
        migrations.DeleteModel(
            name='NzdUsdH4',
        ),
        migrations.DeleteModel(
            name='NzdUsdH8',
        ),
        migrations.DeleteModel(
            name='OilDaily',
        ),
        migrations.DeleteModel(
            name='SpDaily',
        ),
        migrations.DeleteModel(
            name='UsdCadH4',
        ),
        migrations.DeleteModel(
            name='UsdCadH8',
        ),
        migrations.DeleteModel(
            name='UsdChfH4',
        ),
        migrations.DeleteModel(
            name='UsdChfH8',
        ),
        migrations.DeleteModel(
            name='UsdJpyH4',
        ),
        migrations.DeleteModel(
            name='UsdJpyH8',
        ),
    ]
