# Generated by Django 2.2.1 on 2019-09-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_auto_20190926_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoldDaily',
            new_name='GoldUsdDaily',
        ),
    ]
