# Generated by Django 2.2.1 on 2019-09-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0020_auto_20190926_2213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoldUsdDaily',
            new_name='XauUsdDaily',
        ),
    ]
